### ISSUE TITLE
Nice Work!

### ISSUE THREAD

**Issue by xseano** [Spiderlover/Toontown-Crystal#2]
Hi Spiderlover,

I have noticed that you have some experience with the Astron Panda3D Python SDK, I was wondering if I could ask you a couple questions regarding a somewhat secret topic? Is there anyway I could get in contact with you? Please let me know.

Thanks,
Sean

**Comment by Spiderlover** [comment]
sure, you can contact me at josh.zimmer4 on Skype. If you have Discord, you can also contact me at Josh Zimmer #6938

**Comment by xseano** [comment]
Cool, thanks!

**Comment by Spiderlover** [comment]
your welcome
